-- MySQL Script generated by MySQL Workbench
-- Wed Mar 27 12:27:45 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE= 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION' ;

-- -----------------------------------------------------
-- Schema ESTACION
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS ESTACION /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE ESTACION;

-- -----------------------------------------------------
-- Table  ESTACION . Estaciones 
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Estaciones`;
/*!40101 SET @saved_cs_client = @@character_set_client */;
SET character_set_client = utf8mb4 ;
CREATE TABLE Estaciones (
  Id int NOT NULL AUTO_INCREMENT,
  Marca VARCHAR(45) NOT NULL,
  Modelo VARCHAR(45) NOT NULL,
  IP CHAR(15) NOT NULL,
  Tipo_Conex VARCHAR(45) NOT NULL,
  Ubi VARCHAR(45) NOT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX Id_UNIQUE (Id ASC))
ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40101 SET @saved_cs_client = @@character_set_client */;
SET character_set_client = utf8mb4 ;
-- -----------------------------------------------------
-- Table  ESTACION . Sensores 
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sensores`;
/*!40101 SET @saved_cs_client = @@character_set_client */;
SET character_set_client = utf8mb4 ;
CREATE TABLE `Sensores` (
  Id int NOT NULL AUTO_INCREMENT,
  Id_Estacion int NOT NULL,
  Modelo VARCHAR(45) NOT NULL,
  Nombre varchar(250) NOT NULL,
  PRIMARY KEY (Id),
    CONSTRAINT fk_estacion_Sensores
    FOREIGN KEY (Id_Estacion)
    REFERENCES ESTACION.Estaciones (Id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40101 SET @saved_cs_client = @@character_set_client */;
SET character_set_client = utf8mb4 ;
-- -----------------------------------------------------
-- Table  ESTACION . Variables 
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Variables`;
/*!40101 SET @saved_cs_client = @@character_set_client */;
SET character_set_client = utf8mb4 ;
CREATE TABLE `Variables` (
  Id int NOT NULL AUTO_INCREMENT,
  Nombre VARCHAR(45) NOT NULL,
  Ud_Med VARCHAR(45) NOT NULL,
  PRIMARY KEY (Id))
ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40101 SET @saved_cs_client = @@character_set_client */;
SET character_set_client = utf8mb4 ;
-- -----------------------------------------------------
-- Table  ESTACION .  Asignaciones 
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Asignaciones`;
/*!40101 SET @saved_cs_client = @@character_set_client */;
SET character_set_client = utf8mb4 ;
CREATE TABLE `Asignaciones` (
  Sensores_Id int NOT NULL,
  Variables_Id int NOT NULL,
  PRIMARY KEY (Sensores_Id, Variables_Id),
  INDEX fk_Asignaciones_Sensores1_idx (Sensores_Id ASC),
  INDEX fk_Asignaciones_Variables1_idx (Variables_Id ASC),
  CONSTRAINT fk_Asignaciones_Sensores1
    FOREIGN KEY (Sensores_Id)
    REFERENCES ESTACION.Sensores (Id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Asignaciones_Variables1
    FOREIGN KEY (Variables_Id)
    REFERENCES ESTACION.Variables (Id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40101 SET @saved_cs_client = @@character_set_client */;
SET character_set_client = utf8mb4 ;
-- -----------------------------------------------------
-- Table  ESTACION . Medidas 
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Medidas`;
/*!40101 SET @saved_cs_client = @@character_set_client */;
SET character_set_client = utf8mb4 ;
CREATE TABLE `Medidas`(
   Sensores_Id  int NOT NULL,
   Variables_Id  int NOT NULL,
   Fecha_Hora  TIMESTAMP NOT NULL,
   Valor  VARCHAR(45) NOT NULL,
  PRIMARY KEY ( Sensores_Id ,  Variables_Id,  Fecha_Hora),
  INDEX  fk_Sensores_has_Variables_Variable_meteorolo_idx  ( Variables_Id  ASC),
  INDEX  fk_Sensores_has_Variables_Sensores1_idx  ( Sensores_Id  ASC),
  CONSTRAINT  fk_Sensores_has_Variables_Sensores1 
    FOREIGN KEY ( Sensores_Id )
    REFERENCES  Sensores  ( Id )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT  fk_Sensores_has_Variables_Variable_meteorologi1 
    FOREIGN KEY ( Variables_Id )
    REFERENCES  Variables  ( Id )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;